### ISSUE TITLE
Take-over request

### ISSUE THREAD

**Issue by bossanova808** [Memphiz/script.xbmc.unpausejumpback#13]
Hi Memphiz....hope you are well.  Seems a very long time ago you helped me battle that libnfs bug!

Wondering if you would mind if perhaps I took this addon over - I know you're busy and I think perhaps not super interested in this one (from reading the issues etc).  

With the forthcoming Matrix/Python3 changes, I have taken over a couple of similar/related addons recently (Playback Resumer, Check Previous Episode) - and this is of course very much in the same area.  Both of those just got merged into the Matrix repo, and I'd like to get this one ready for that as well, as I still find it a very handy thing (quick and dirty though it might be!).

Ideally, I'd like to take it over so I can manage issues, PRs and so on, more directly.

Of course I understand if not, and can submit a PR here with the changes if you prefer that and see yourself as having the time to take it forward.

Either way, I am in the process of tidying it up for Python3 (pinching some work from a fork I see here) and would add github actions and so on.

Let me know what you think, and all the best to you!

**Comment by bossanova808** [comment]
Ok, so I've done the work and this is basically ready to submit - https://github.com/bossanova808/script.xbmc.unpausejumpback

(...I did move myself in front of you in the addon.xml, not because I care about credit but just so folks know where to look to report issues etc.  No problem if that is not ok, just let me know).

I think the first Matrix alphas are not for away now so I'd like to get on to submitting this if possible.  Please let me know if you have any objections....

**Comment by Memphiz** [comment]
Sorry for some reason i had no email notification about that one ... thx for working on this and on python3 support in general.
